In [95]:
import pandas as pd

df = pd.read_csv('NHS-5_2019-20.csv')
pd.options.display.max_columns = 110

df.columns = range(df.shape[1])


# df[1] = pd.factorize(df[1])[0]
# df.drop([0,2,3], axis=0)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107
0,India,Arunachal Pradesh,Longding,"Calendar Year (Jan - Dec), 2019",37.700,34.100,68.600,49.000,3778.000,65.000,4.200,NaN,5.100,0.900,22.600,52.700,75.200,59.700,59.700,52.700,34.100,74.500,61.500,0.0,85.8,14.900,0.000,38.40,NaN,54.200,0.0,4.200,14.200,15.800,13.800,20.600,58.000,88.700,66.100,55.500,NaN,NaN,NaN,NaN,3.900,86.500,57.200,0.000,0.000,0.000,63.200,21.300,17.300,0.900,22.400,99.300,23.800,7.100,0.800,64.50,62.800,0.00,55.200,56.100,7.30,14.500,6.700,31.100,22.300,8.30,33.400,7.100,65.800,39.600,57.100,78.400,NaN,35.000,16.000,29.900,83.500,62.50,97.400,19.100,0.500,0.800,97.000,961.000,926.000,20.000,7.300,4.500,21.800,16.000,2.200,92.000,7.90,70.200,13.700,62.00,4.000,27.700,5.300,10.500,4.90,20.500,15.700,4.100
1,India,Andaman And Nicobar Islands,South Andamans,"Calendar Year (Jan - Dec), 2019",43.200,57.700,57.100,50.500,3460.000,96.900,37.100,79.1,29.600,0.500,22.300,76.300,96.600,94.800,85.300,79.000,0.000,100.000,81.700,4.3,93.1,33.700,50.800,43.40,0.0,84.000,0.0,7.200,3.500,21.100,17.400,12.600,51.100,96.500,0.000,89.800,0.0,0.0,0.0,77.300,10.600,88.200,92.200,0.700,1.300,8.000,84.700,34.000,31.200,0.000,91.900,99.700,1.200,2.800,0.300,99.50,83.800,0.00,32.800,50.800,9.30,18.100,7.800,26.900,17.900,6.10,81.000,61.900,79.400,85.900,88.100,92.100,0.0,57.600,1.800,21.000,89.300,97.90,99.600,0.000,6.000,0.000,98.900,935.000,967.000,23.500,17.600,8.600,1.700,19.600,2.800,98.200,17.10,86.700,39.000,78.20,10.000,57.500,7.500,18.400,9.50,23.000,12.700,4.900
2,India,Arunachal Pradesh,Lower Dibang Valley,"Calendar Year (Jan - Dec), 2019",39.400,34.600,75.300,56.400,6112.000,93.700,11.000,NaN,10.700,0.000,29.500,73.800,81.000,77.000,79.200,77.800,41.700,89.200,84.400,0.0,100.0,31.400,2.000,51.50,NaN,67.100,NaN,5.000,2.900,14.300,9.700,7.600,59.800,92.600,60.100,58.400,NaN,NaN,NaN,NaN,8.300,94.800,53.600,0.200,0.000,0.200,76.800,28.400,21.400,3.600,57.400,98.700,36.800,12.200,0.400,90.10,86.800,0.00,48.700,52.100,7.10,13.200,5.900,38.100,24.800,12.60,25.800,3.300,56.300,48.600,58.600,87.500,NaN,35.300,3.900,24.500,89.900,99.50,84.400,19.600,2.800,1.000,97.200,884.000,1010.000,23.900,4.900,4.600,20.300,20.600,1.600,96.000,13.80,80.000,16.800,75.10,4.100,51.900,4.600,8.900,4.10,25.600,16.700,8.100
3,India,Andhra Pradesh,Spsr Nellore,"Calendar Year (Jan - Dec), 2019",68.600,59.400,71.900,71.700,1104.000,100.000,42.300,57.5,18.800,3.400,7.400,65.300,80.100,81.100,77.200,69.400,70.900,89.200,81.100,8.8,91.3,18.700,9.600,67.50,0.0,77.000,0.0,0.500,6.900,29.200,27.800,17.200,39.400,88.100,54.700,94.300,0.0,0.0,0.0,72.300,0.300,21.700,84.800,0.800,10.200,6.700,67.900,71.400,19.700,3.000,84.600,85.600,72.300,0.000,0.000,97.00,34.900,0.00,25.900,26.500,7.20,21.100,12.700,25.100,15.300,5.90,76.100,51.800,89.000,73.000,95.500,94.200,0.0,59.600,0.000,20.800,81.800,95.60,99.100,0.000,8.900,3.900,92.800,1011.000,1049.000,6.900,3.100,2.300,0.300,4.400,14.900,84.000,23.80,70.500,39.500,47.60,15.200,38.700,8.200,21.800,12.30,23.000,12.700,4.500
4,India,Arunachal Pradesh,Kamle,"Calendar Year (Jan - Dec), 2019",53.057,39.307,61.912,54.985,10210.742,89.051,19.066,NaN,21.216,1.437,30.992,67.117,84.872,71.452,67.845,75.368,27.033,86.482,78.908,0.0,100.0,34.454,15.051,54.87,NaN,66.643,0.0,12.733,6.579,32.583,11.527,11.716,53.766,86.573,12.101,62.783,NaN,NaN,NaN,45.407,7.696,68.931,24.188,0.512,2.627,0.643,69.426,22.645,14.684,3.554,52.156,99.593,23.574,8.241,2.342,85.78,83.471,0.07,53.408,49.308,7.39,13.108,4.484,36.873,25.139,10.43,17.838,6.273,47.496,36.902,64.246,81.295,NaN,39.687,12.648,23.636,82.213,97.05,94.466,27.062,6.246,3.305,94.278,1297.454,1027.113,25.355,11.263,4.278,24.965,18.565,5.517,92.494,19.36,69.914,23.765,72.82,3.829,44.216,4.492,8.315,3.16,25.606,17.288,7.066
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728,India,Tamil Nadu,Vellore,"Calendar Year (Jan - Dec), 2019",47.200,50.600,65.200,63.200,2272.000,100.000,42.400,43.9,42.100,1.900,8.800,92.700,97.200,94.300,91.200,93.900,80.800,97.000,95.500,13.9,86.1,46.400,16.600,60.90,NaN,71.600,NaN,4.200,2.500,29.800,19.700,13.100,76.400,96.500,NaN,96.700,NaN,NaN,NaN,NaN,0.500,98.900,91.700,0.500,1.800,0.200,80.000,59.500,32.700,0.500,85.300,93.800,71.400,3.100,0.200,99.50,67.600,0.00,23.000,14.400,8.00,21.400,12.400,25.600,16.800,6.40,94.200,84.600,84.400,95.400,98.600,96.800,NaN,50.700,0.000,22.400,76.200,97.70,99.300,NaN,2.800,0.300,100.000,722.000,1070.000,9.900,6.700,3.600,0.300,4.300,4.900,98.500,14.90,81.600,45.400,51.50,11.400,52.500,8.100,20.400,11.10,25.900,14.100,7.100
729,India,Uttar Pradesh,Muzaffarnagar,"Calendar Year (Jan - Dec), 2019",48.800,46.000,73.200,44.900,1747.000,89.900,22.400,33.3,18.700,4.300,18.300,69.500,79.600,75.500,75.500,74.100,62.200,91.100,77.600,4.1,93.8,23.600,4.400,65.40,NaN,72.900,0.0,4.200,9.900,29.800,29.900,20.700,18.200,80.200,61.800,87.300,77.2,29.0,11.6,NaN,24.700,78.800,70.500,0.200,0.200,0.200,69.100,14.400,17.600,4.200,59.800,96.300,8.200,1.600,0.100,87.00,45.000,0.20,13.700,31.700,8.50,14.300,5.800,24.200,16.600,6.80,34.500,8.400,75.500,44.000,88.500,94.000,10.6,46.200,3.600,30.400,80.100,99.90,97.800,40.200,6.400,0.500,96.400,865.000,957.000,16.100,5.000,1.900,0.300,3.700,1.000,78.100,7.30,72.100,28.100,67.70,11.100,41.800,5.500,11.500,5.20,21.600,14.900,5.000
730,India,Jharkhand,Garhwa,"Calendar Year (Jan - Dec), 2019",61.000,62.700,58.300,48.700,2256.000,88.200,10.200,48.8,3.300,3.700,6.200,77.200,82.900,86.000,84.800,78.200,79.300,96.800,86.100,2.2,91.8,29.300,9.700,62.50,NaN,61.200,7.0,0.500,5.300,47.700,40.600,18.900,25.200,63.000,87.500,70.600,51.2,18.8,18.6,69.800,0.900,48.000,35.800,0.200,0.900,0.200,60.500,44.200,18.400,4.400,24.700,97.500,55.300,0.800,0.500,84.00,67.600,0.20,29.200,46.700,7.10,15.700,7.700,23.400,13.500,7.90,16.800,3.300,66.300,29.800,70.300,92.100,NaN,62.900,0.400,33.300,54.100,92.50,85.000,58.900,6.600,0.200,87.100,829.000,1108.000,6.400,12.300,5.700,3.000,4.800,8.700,59.300,31.30,59.600,13.600,35.50,28.800,31.000,7.000,12.300,4.70,18.300,11.100,5.300
731,India,Uttarakhand,Uttar Kashi,"Calendar Year (Jan - Dec), 2019",66.100,60.900,73.800,60.200,3168.000,84.500,6.200,28.7,4.800,2.500,7.400,81.800,91.500,94.300,94.300,86.200,44.400,89.900,95.800,0.0,100.0,29.400,4.200,73.60,NaN,55.600,0.0,2.700,5.400,34.100,23.500,10.600,61.700,94.100,52.400,72.400,NaN,NaN,NaN,NaN,11.700,51.500,81.100,0.100,0.100,0.800,69.000,42.300,34.200,0.400,32.600,87.200,80.300,1.300,0.500,85.90,77.000,2.70,26.900,35.100,4.40,10.900,6.000,24.400,16.500,6.30,46.900,18.900,77.100,66.800,72.000,95.300,NaN,60.800,1.900,25.000,75.700,96.10,99.600,64.000,4.800,1.700,99.600,869.000,1024.000,7.600,7.700,3.900,0.500,2.500,4.800,90.200,5.70,80.100,21.500,59.70,12.900,53.600,4.500,8.200,3.50,19.000,12.500,5.000
732,India,Bihar,Pashchim Champaran,"Calendar Year (Jan - Dec), 2019",56.300,50.600,50.700,40.200,1882.000,78.400,6.400,25.2,2.800,5.800,9.400,62.100,82.700,74.300,73.400,74.700,1.000,88.800,79.900,2.0,96.8,21.400,9.200,61.60,0.0,62.000,1.4,2.400,5.400,43.500,30.300,13.200,25.900,71.500,64.200,64.100,59.7,56.8,16.4,60.200,2.700,38.900,29.400,0.000,0.300,0.000,59.800,34.500,21.000,4.000,31.400,97.700,20.000,0.200,0.700,79.50,60.600,0.00,10.800,48.100,5.90,13.400,6.800,22.600,12.300,7.80,9.900,6.500,55.000,25.400,57.300,89.700,0.0,49.800,1.000,36.500,43.300,99.70,93.500,61.400,22.100,6.600,83.900,904.000,1088.000,13.600,12.100,6.300,0.900,5.900,12.500,42.900,39.10,52.500,20.600,59.40,24.600,21.600,4.300,9.300,4.50,18.100,11.300,5.100

In [96]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import statsmodels.api as sm 
import seaborn as sns 

x1 = df.drop([0, 3], axis=1)

x1.iloc[:, 2:] = x1.iloc[:, 2:].apply(lambda col: col.fillna(col.mean()), axis=0)


df = x1
df

,1,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107
0,Arunachal Pradesh,Longding,37.700,34.100,68.600,49.000,3778.000,65.000,4.200,43.894499,5.100,0.900,22.600,52.700,75.200,59.700,59.700,52.700,34.100,74.500,61.500,0.0,85.8,14.900,0.000,38.40,7.140397,54.200,0.000000,4.200,14.200,15.800,13.800,20.600,58.000,88.700,66.100000,55.500,31.809972,28.810246,15.021765,57.096954,3.900,86.500,57.200,0.000,0.000,0.000,63.200,21.300,17.300,0.900,22.400,99.300,23.800,7.100,0.800,64.50,62.800,0.00,55.200,56.100,7.30,14.500,6.700,31.100,22.300,8.30,33.400,7.100,65.800,39.600,57.100,78.400,2.114038,35.000,16.000,29.900,83.500,62.50,97.400,19.100000,0.500,0.800,97.000,961.000,926.000,20.000,7.300,4.500,21.800,16.000,2.200,92.000,7.90,70.200,13.700,62.00,4.000,27.700,5.300,10.500,4.90,20.500,15.700,4.100
1,Andaman And Nicobar Islands,South Andamans,43.200,57.700,57.100,50.500,3460.000,96.900,37.100,79.100000,29.600,0.500,22.300,76.300,96.600,94.800,85.300,79.000,0.000,100.000,81.700,4.3,93.1,33.700,50.800,43.40,0.000000,84.000,0.000000,7.200,3.500,21.100,17.400,12.600,51.100,96.500,0.000000,89.800,0.000000,0.000000,0.000000,77.300000,10.600,88.200,92.200,0.700,1.300,8.000,84.700,34.000,31.200,0.000,91.900,99.700,1.200,2.800,0.300,99.50,83.800,0.00,32.800,50.800,9.30,18.100,7.800,26.900,17.900,6.10,81.000,61.900,79.400,85.900,88.100,92.100,0.000000,57.600,1.800,21.000,89.300,97.90,99.600,0.000000,6.000,0.000,98.900,935.000,967.000,23.500,17.600,8.600,1.700,19.600,2.800,98.200,17.10,86.700,39.000,78.20,10.000,57.500,7.500,18.400,9.50,23.000,12.700,4.900
2,Arunachal Pradesh,Lower Dibang Valley,39.400,34.600,75.300,56.400,6112.000,93.700,11.000,43.894499,10.700,0.000,29.500,73.800,81.000,77.000,79.200,77.800,41.700,89.200,84.400,0.0,100.0,31.400,2.000,51.50,7.140397,67.100,2.149331,5.000,2.900,14.300,9.700,7.600,59.800,92.600,60.100000,58.400,31.809972,28.810246,15.021765,57.096954,8.300,94.800,53.600,0.200,0.000,0.200,76.800,28.400,21.400,3.600,57.400,98.700,36.800,12.200,0.400,90.10,86.800,0.00,48.700,52.100,7.10,13.200,5.900,38.100,24.800,12.60,25.800,3.300,56.300,48.600,58.600,87.500,2.114038,35.300,3.900,24.500,89.900,99.50,84.400,19.600000,2.800,1.000,97.200,884.000,1010.000,23.900,4.900,4.600,20.300,20.600,1.600,96.000,13.80,80.000,16.800,75.10,4.100,51.900,4.600,8.900,4.10,25.600,16.700,8.100
3,Andhra Pradesh,Spsr Nellore,68.600,59.400,71.900,71.700,1104.000,100.000,42.300,57.500000,18.800,3.400,7.400,65.300,80.100,81.100,77.200,69.400,70.900,89.200,81.100,8.8,91.3,18.700,9.600,67.50,0.000000,77.000,0.000000,0.500,6.900,29.200,27.800,17.200,39.400,88.100,54.700000,94.300,0.000000,0.000000,0.000000,72.300000,0.300,21.700,84.800,0.800,10.200,6.700,67.900,71.400,19.700,3.000,84.600,85.600,72.300,0.000,0.000,97.00,34.900,0.00,25.900,26.500,7.20,21.100,12.700,25.100,15.300,5.90,76.100,51.800,89.000,73.000,95.500,94.200,0.000000,59.600,0.000,20.800,81.800,95.60,99.100,0.000000,8.900,3.900,92.800,1011.000,1049.000,6.900,3.100,2.300,0.300,4.400,14.900,84.000,23.80,70.500,39.500,47.60,15.200,38.700,8.200,21.800,12.30,23.000,12.700,4.500
4,Arunachal Pradesh,Kamle,53.057,39.307,61.912,54.985,10210.742,89.051,19.066,43.894499,21.216,1.437,30.992,67.117,84.872,71.452,67.845,75.368,27.033,86.482,78.908,0.0,100.0,34.454,15.051,54.87,7.140397,66.643,0.000000,12.733,6.579,32.583,11.527,11.716,53.766,86.573,12.101000,62.783,31.809972,28.810246,15.021765,45.407000,7.696,68.931,24.188,0.512,2.627,0.643,69.426,22.645,14.684,3.554,52.156,99.593,23.574,8.241,2.342,85.78,83.471,0.07,53.408,49.308,7.39,13.108,4.484,36.873,25.139,10.43,17.838,6.273,47.496,36.902,64.246,81.295,2.114038,39.687,12.648,23.636,82.213,97.05,94.466,27.062000,6.246,3.305,94.278,1297.454,1027.113,25.355,11.263,4.278,24.965,18.565,5.517,92.494,19.36,69.914,23.765,72.82,3.829,44.216,4.492,8.315,3.16,25.606,17.288,7.066
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728,Tamil Nadu,Vellore,47.200,50.600,65.200,63.200,2272.000,100.000,42.400,43.900000,42.100,1.900,8.800,92.700,97.200,94.300,91.200,93.900,80.800,97.000,95.500,13.9,86.1,46.400,16.600,60.90,7.140397,71.600,2.149331,4.200,2.500,29.800,19.700,13.100,76.400,96.500,47.530962,96.700,31.809972,28.810246,15.021765,57.096954,0.500,98.900,91.700,0.500,1.800,0.200,80.000,59.500,32.700,0.500,85.300,93.800,71.400,3.100,0.200,99.50,67.600,0.00,23.000,14.400,8.00,21.400,12.400,25.600,16.800,6.40,94.200,84.600,84.400,95.400,98.600,96.800,2.114038,50.700,0.000,22.400,76.200,97.70,99.300,44.312841,2.800,0.300,100.000,722.000,1070.000,9.900,6.700,3.600,0.300,4.300,4.900,98.500,14.90,81.600,45.400,51.50,11.400,52.500,8.100,20.400,11.10,25.900,14.100,7.100
729,Uttar Pradesh,Muzaffarnagar,48.800,46.000,73.200,44.900,1747.000,89.900,22.400,33.300000,18.700,4.300,18.300,69.500,79.600,75.500,75.500,74.100,62.200,91.100,77.600,4.1,93.8,23.600,4.400,65.40,7.140397,72.900,0.000000,4.200,9.900,29.800,29.900,20.700,18.200,80.200,61.800000,87.300,77.200000,29.000000,11.600000,57.096954,24.700,78.800,70.500,0.200,0.200,0.200,69.100,14.400,17.600,4.200,59.800,96.300,8.200,1.600,0.100,87.00,45.000,0.20,13.700,31.700,8.50,14.300,5.800,24.200,16.600,6.80,34.500,8.400,75.500,44.000,88.500,94.000,10.600000,46.200,3.600,30.400,80.100,99.90,97.800,40.200000,6.400,0.500,96.400,865.000,957.000,16.100,5.000,1.900,0.300,3.700,1.000,78.100,7.30,72.100,28.100,67.70,11.100,41.800,5.500,11.500,5.20,21.600,14.900,5.000
730,Jharkhand,Garhwa,61.000,62.700,58.300,48.700,2256.000,88.200,10.200,48.800000,3.300,3.700,6.200,77.200,82.900,86.000,84.800,78.200,79.300,96.800,86.100,2.2,91.8,29.300,9.700,62.50,7.140397,61.200,7.000000,0.500,5.300,47.700,40.600,18.900,25.200,63.000,87.500000,70.600,51.200000,18.800000,18.600000,69.800000,0.900,48.000,35.800,0.200,0.900,0.200,60.500,44.200,18.400,4.400,24.700,97.500,55.300,0.800,0.500,84.00,67.600,0.20,29.200,46.700,7.10,15.700,7.700,23.400,13.500,7.90,16.800,3.300,66.300,29.800,70.300,92.100,2.114038,62.900,0.400,33.300,54.100,92.50,85.000,58.900000,6.600,0.200,87.100,829.000,1108.000,6.400,12.300,5.700,3.000,4.800,8.700,59.300,31.30,59.600,13.600,35.50,28.800,31.000,7.000,12.300,4.70,18.300,11.100,5.300
731,Uttarakhand,Uttar Kashi,66.100,60.900,73.800,60.200,3168.000,84.500,6.200,28.700000,4.800,2.500,7.400,81.800,91.500,94.300,94.300,86.200,44.400,89.900,95.800,0.0,100.0,29.400,4.200,73.60,7.140397,55.600,0.000000,2.700,5.400,34.100,23.500,10.600,61.700,94.100,52.400000,72.400,31.809972,28.810246,15.021765,57.096954,11.700,51.500,81.100,0.100,0.100,0.800,69.000,42.300,34.200,0.400,32.600,87.200,80.300,1.300,0.500,85.90,77.000,2.70,26.900,35.100,4.40,10.900,6.000,24.400,16.500,6.30,46.900,18.900,77.100,66.800,72.000,95.300,2.114038,60.800,1.900,25.000,75.700,96.10,99.600,64.000000,4.800,1.700,99.600,869.000,1024.000,7.600,7.700,3.900,0.500,2.500,4.800,90.200,5.70,80.100,21.500,59.70,12.900,53.600,4.500,8.200,3.50,19.000,12.500,5.000
732,Bihar,Pashchim Champaran,56.300,50.600,50.700,40.200,1882.000,78.400,6.400,25.200000,2.800,5.800,9.400,62.100,82.700,74.300,73.400,74.700,1.000,88.800,79.900,2.0,96.8,21.400,9.200,61.60,0.000000,62.000,1.400000,2.400,5.400,43.500,30.300,13.200,25.900,71.500,64.200000,64.100,59.700000,56.800000,16.400000,60.200000,2.700,38.900,29.400,0.000,0.300,0.000,59.800,34.500,21.000,4.000,31.400,97.700,20.000,0.200,0.700,79.50,60.600,0.00,10.800,48.100,5.90,13.400,6.800,22.600,12.300,7.80,9.900,6.500,55.000,25.400,57.300,89.700,0.000000,49.800,1.000,36.500,43.300,99.70,93.500,61.400000,22.100,6.600,83.900,904.000,1088.000,13.600,12.100,6.300,0.900,5.900,12.500,42.900,39.10,52.500,20.600,59.40,24.600,21.600,4.300,9.300,4.50,18.100,11.300,5.100

## Weights to ohd indicators(DistrictWise) with IMR,Hospitals & Life Expectency

### Putting the values of IMR, Hospitals & LE of a particular state to each districts of that state.

In [97]:
IMR_data = pd.read_csv("supreme_merged_file.csv")
# IMR_data
df

,1,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107
0,Arunachal Pradesh,Longding,37.700,34.100,68.600,49.000,3778.000,65.000,4.200,43.894499,5.100,0.900,22.600,52.700,75.200,59.700,59.700,52.700,34.100,74.500,61.500,0.0,85.8,14.900,0.000,38.40,7.140397,54.200,0.000000,4.200,14.200,15.800,13.800,20.600,58.000,88.700,66.100000,55.500,31.809972,28.810246,15.021765,57.096954,3.900,86.500,57.200,0.000,0.000,0.000,63.200,21.300,17.300,0.900,22.400,99.300,23.800,7.100,0.800,64.50,62.800,0.00,55.200,56.100,7.30,14.500,6.700,31.100,22.300,8.30,33.400,7.100,65.800,39.600,57.100,78.400,2.114038,35.000,16.000,29.900,83.500,62.50,97.400,19.100000,0.500,0.800,97.000,961.000,926.000,20.000,7.300,4.500,21.800,16.000,2.200,92.000,7.90,70.200,13.700,62.00,4.000,27.700,5.300,10.500,4.90,20.500,15.700,4.100
1,Andaman And Nicobar Islands,South Andamans,43.200,57.700,57.100,50.500,3460.000,96.900,37.100,79.100000,29.600,0.500,22.300,76.300,96.600,94.800,85.300,79.000,0.000,100.000,81.700,4.3,93.1,33.700,50.800,43.40,0.000000,84.000,0.000000,7.200,3.500,21.100,17.400,12.600,51.100,96.500,0.000000,89.800,0.000000,0.000000,0.000000,77.300000,10.600,88.200,92.200,0.700,1.300,8.000,84.700,34.000,31.200,0.000,91.900,99.700,1.200,2.800,0.300,99.50,83.800,0.00,32.800,50.800,9.30,18.100,7.800,26.900,17.900,6.10,81.000,61.900,79.400,85.900,88.100,92.100,0.000000,57.600,1.800,21.000,89.300,97.90,99.600,0.000000,6.000,0.000,98.900,935.000,967.000,23.500,17.600,8.600,1.700,19.600,2.800,98.200,17.10,86.700,39.000,78.20,10.000,57.500,7.500,18.400,9.50,23.000,12.700,4.900
2,Arunachal Pradesh,Lower Dibang Valley,39.400,34.600,75.300,56.400,6112.000,93.700,11.000,43.894499,10.700,0.000,29.500,73.800,81.000,77.000,79.200,77.800,41.700,89.200,84.400,0.0,100.0,31.400,2.000,51.50,7.140397,67.100,2.149331,5.000,2.900,14.300,9.700,7.600,59.800,92.600,60.100000,58.400,31.809972,28.810246,15.021765,57.096954,8.300,94.800,53.600,0.200,0.000,0.200,76.800,28.400,21.400,3.600,57.400,98.700,36.800,12.200,0.400,90.10,86.800,0.00,48.700,52.100,7.10,13.200,5.900,38.100,24.800,12.60,25.800,3.300,56.300,48.600,58.600,87.500,2.114038,35.300,3.900,24.500,89.900,99.50,84.400,19.600000,2.800,1.000,97.200,884.000,1010.000,23.900,4.900,4.600,20.300,20.600,1.600,96.000,13.80,80.000,16.800,75.10,4.100,51.900,4.600,8.900,4.10,25.600,16.700,8.100
3,Andhra Pradesh,Spsr Nellore,68.600,59.400,71.900,71.700,1104.000,100.000,42.300,57.500000,18.800,3.400,7.400,65.300,80.100,81.100,77.200,69.400,70.900,89.200,81.100,8.8,91.3,18.700,9.600,67.50,0.000000,77.000,0.000000,0.500,6.900,29.200,27.800,17.200,39.400,88.100,54.700000,94.300,0.000000,0.000000,0.000000,72.300000,0.300,21.700,84.800,0.800,10.200,6.700,67.900,71.400,19.700,3.000,84.600,85.600,72.300,0.000,0.000,97.00,34.900,0.00,25.900,26.500,7.20,21.100,12.700,25.100,15.300,5.90,76.100,51.800,89.000,73.000,95.500,94.200,0.000000,59.600,0.000,20.800,81.800,95.60,99.100,0.000000,8.900,3.900,92.800,1011.000,1049.000,6.900,3.100,2.300,0.300,4.400,14.900,84.000,23.80,70.500,39.500,47.60,15.200,38.700,8.200,21.800,12.30,23.000,12.700,4.500
4,Arunachal Pradesh,Kamle,53.057,39.307,61.912,54.985,10210.742,89.051,19.066,43.894499,21.216,1.437,30.992,67.117,84.872,71.452,67.845,75.368,27.033,86.482,78.908,0.0,100.0,34.454,15.051,54.87,7.140397,66.643,0.000000,12.733,6.579,32.583,11.527,11.716,53.766,86.573,12.101000,62.783,31.809972,28.810246,15.021765,45.407000,7.696,68.931,24.188,0.512,2.627,0.643,69.426,22.645,14.684,3.554,52.156,99.593,23.574,8.241,2.342,85.78,83.471,0.07,53.408,49.308,7.39,13.108,4.484,36.873,25.139,10.43,17.838,6.273,47.496,36.902,64.246,81.295,2.114038,39.687,12.648,23.636,82.213,97.05,94.466,27.062000,6.246,3.305,94.278,1297.454,1027.113,25.355,11.263,4.278,24.965,18.565,5.517,92.494,19.36,69.914,23.765,72.82,3.829,44.216,4.492,8.315,3.16,25.606,17.288,7.066
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728,Tamil Nadu,Vellore,47.200,50.600,65.200,63.200,2272.000,100.000,42.400,43.900000,42.100,1.900,8.800,92.700,97.200,94.300,91.200,93.900,80.800,97.000,95.500,13.9,86.1,46.400,16.600,60.90,7.140397,71.600,2.149331,4.200,2.500,29.800,19.700,13.100,76.400,96.500,47.530962,96.700,31.809972,28.810246,15.021765,57.096954,0.500,98.900,91.700,0.500,1.800,0.200,80.000,59.500,32.700,0.500,85.300,93.800,71.400,3.100,0.200,99.50,67.600,0.00,23.000,14.400,8.00,21.400,12.400,25.600,16.800,6.40,94.200,84.600,84.400,95.400,98.600,96.800,2.114038,50.700,0.000,22.400,76.200,97.70,99.300,44.312841,2.800,0.300,100.000,722.000,1070.000,9.900,6.700,3.600,0.300,4.300,4.900,98.500,14.90,81.600,45.400,51.50,11.400,52.500,8.100,20.400,11.10,25.900,14.100,7.100
729,Uttar Pradesh,Muzaffarnagar,48.800,46.000,73.200,44.900,1747.000,89.900,22.400,33.300000,18.700,4.300,18.300,69.500,79.600,75.500,75.500,74.100,62.200,91.100,77.600,4.1,93.8,23.600,4.400,65.40,7.140397,72.900,0.000000,4.200,9.900,29.800,29.900,20.700,18.200,80.200,61.800000,87.300,77.200000,29.000000,11.600000,57.096954,24.700,78.800,70.500,0.200,0.200,0.200,69.100,14.400,17.600,4.200,59.800,96.300,8.200,1.600,0.100,87.00,45.000,0.20,13.700,31.700,8.50,14.300,5.800,24.200,16.600,6.80,34.500,8.400,75.500,44.000,88.500,94.000,10.600000,46.200,3.600,30.400,80.100,99.90,97.800,40.200000,6.400,0.500,96.400,865.000,957.000,16.100,5.000,1.900,0.300,3.700,1.000,78.100,7.30,72.100,28.100,67.70,11.100,41.800,5.500,11.500,5.20,21.600,14.900,5.000
730,Jharkhand,Garhwa,61.000,62.700,58.300,48.700,2256.000,88.200,10.200,48.800000,3.300,3.700,6.200,77.200,82.900,86.000,84.800,78.200,79.300,96.800,86.100,2.2,91.8,29.300,9.700,62.50,7.140397,61.200,7.000000,0.500,5.300,47.700,40.600,18.900,25.200,63.000,87.500000,70.600,51.200000,18.800000,18.600000,69.800000,0.900,48.000,35.800,0.200,0.900,0.200,60.500,44.200,18.400,4.400,24.700,97.500,55.300,0.800,0.500,84.00,67.600,0.20,29.200,46.700,7.10,15.700,7.700,23.400,13.500,7.90,16.800,3.300,66.300,29.800,70.300,92.100,2.114038,62.900,0.400,33.300,54.100,92.50,85.000,58.900000,6.600,0.200,87.100,829.000,1108.000,6.400,12.300,5.700,3.000,4.800,8.700,59.300,31.30,59.600,13.600,35.50,28.800,31.000,7.000,12.300,4.70,18.300,11.100,5.300
731,Uttarakhand,Uttar Kashi,66.100,60.900,73.800,60.200,3168.000,84.500,6.200,28.700000,4.800,2.500,7.400,81.800,91.500,94.300,94.300,86.200,44.400,89.900,95.800,0.0,100.0,29.400,4.200,73.60,7.140397,55.600,0.000000,2.700,5.400,34.100,23.500,10.600,61.700,94.100,52.400000,72.400,31.809972,28.810246,15.021765,57.096954,11.700,51.500,81.100,0.100,0.100,0.800,69.000,42.300,34.200,0.400,32.600,87.200,80.300,1.300,0.500,85.90,77.000,2.70,26.900,35.100,4.40,10.900,6.000,24.400,16.500,6.30,46.900,18.900,77.100,66.800,72.000,95.300,2.114038,60.800,1.900,25.000,75.700,96.10,99.600,64.000000,4.800,1.700,99.600,869.000,1024.000,7.600,7.700,3.900,0.500,2.500,4.800,90.200,5.70,80.100,21.500,59.70,12.900,53.600,4.500,8.200,3.50,19.000,12.500,5.000
732,Bihar,Pashchim Champaran,56.300,50.600,50.700,40.200,1882.000,78.400,6.400,25.200000,2.800,5.800,9.400,62.100,82.700,74.300,73.400,74.700,1.000,88.800,79.900,2.0,96.8,21.400,9.200,61.60,0.000000,62.000,1.400000,2.400,5.400,43.500,30.300,13.200,25.900,71.500,64.200000,64.100,59.700000,56.800000,16.400000,60.200000,2.700,38.900,29.400,0.000,0.300,0.000,59.800,34.500,21.000,4.000,31.400,97.700,20.000,0.200,0.700,79.50,60.600,0.00,10.800,48.100,5.90,13.400,6.800,22.600,12.300,7.80,9.900,6.500,55.000,25.400,57.300,89.700,0.000000,49.800,1.000,36.500,43.300,99.70,93.500,61.400000,22.100,6.600,83.900,904.000,1088.000,13.600,12.100,6.300,0.900,5.900,12.500,42.900,39.10,52.500,20.600,59.40,24.600,21.600,4.300,9.300,4.50,18.100,11.300,5.100

### Overall health Condition

In [98]:
df = df[[1, 2,73, 74, 39, 4, 33, 34, 35, 22, 19, 80, 81, 97]]
df
# df = df.drop(columns=[2])
# df.to_csv("state_ohd_indicators.csv")

,1,2,73,74,39,4,33,34,35,22,19,80,81,97
0,Arunachal Pradesh,Longding,39.600,57.100,55.500,37.700,15.800,13.800,20.600,61.500,52.700,83.500,62.50,70.200
1,Andaman And Nicobar Islands,South Andamans,85.900,88.100,89.800,43.200,21.100,17.400,12.600,81.700,79.000,89.300,97.90,86.700
2,Arunachal Pradesh,Lower Dibang Valley,48.600,58.600,58.400,39.400,14.300,9.700,7.600,84.400,77.800,89.900,99.50,80.000
3,Andhra Pradesh,Spsr Nellore,73.000,95.500,94.300,68.600,29.200,27.800,17.200,81.100,69.400,81.800,95.60,70.500
4,Arunachal Pradesh,Kamle,36.902,64.246,62.783,53.057,32.583,11.527,11.716,78.908,75.368,82.213,97.05,69.914
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728,Tamil Nadu,Vellore,95.400,98.600,96.700,47.200,29.800,19.700,13.100,95.500,93.900,76.200,97.70,81.600
729,Uttar Pradesh,Muzaffarnagar,44.000,88.500,87.300,48.800,29.800,29.900,20.700,77.600,74.100,80.100,99.90,72.100
730,Jharkhand,Garhwa,29.800,70.300,70.600,61.000,47.700,40.600,18.900,86.100,78.200,54.100,92.50,59.600
731,Uttarakhand,Uttar Kashi,66.800,72.000,72.400,66.100,34.100,23.500,10.600,95.800,86.200,75.700,96.10,80.100
732,Bihar,Pashchim Champaran,25.400,57.300,64.100,56.300,43.500,30.300,13.200,79.900,74.700,43.300,99.70,52.500

In [120]:
df = df.sort_values(1)
IMR_data

,State,Total District Hospitals,Life Expectancy,IMR
0,Andaman And Nicobar Islands,3,70.43913,19.027778
1,Andhra Pradesh,14,70.00000,24.000000
2,Arunachal Pradesh,17,70.43913,21.000000
3,Assam,25,66.90000,36.000000
4,Bihar,36,69.10000,27.000000
5,Chandigarh,1,70.43913,8.000000
6,Chhattisgarh,26,65.20000,38.000000
7,Delhi,47,75.30000,19.027778
8,Goa,2,70.43913,5.000000
9,Gujarat,22,69.90000,23.000000
10,Haryana,22,69.80000,28.000000
11,Himachal Pradesh,12,72.90000,17.000000
12,Jammu And Kashmir,21,74.00000,19.027778
13,Jharkhand,23,69.10000,25.000000
14,Karnataka,15,69.40000,19.000000
15,Kerala,18,75.30000,6.000000
16,Ladakh,2,74.00000,16.000000
17,Lakshadweep,1,70.43913,9.000000
18,Madhya Pradesh,51,66.50000,43.000000
19,Maharashtra,23,72.50000,16.000000
20,Manipur,9,70.43913,6.000000
21,Meghalaya,11,70.43913,29.000000
22,Mizoram,9,70.43913,3.000000
23,Nagaland,11,70.43913,4.000000
24,Odisha,32,69.30000,36.000000
25,Puducherry,5,70.43913,6.000000
26,Punjab,22,72.70000,18.000000
27,Rajasthan,27,68.70000,32.000000
28,Sikkim,4,70.43913,5.000000
29,Tamil Nadu,31,72.10000,13.000000
30,Telangana,6,69.60000,21.000000
31,The Dadra And Nagar Haveli And Daman And Diu,3,70.43913,19.027778
32,Tripura,7,70.43913,18.000000
33,Uttar Pradesh,157,65.30000,38.000000
34,Uttarakhand,18,70.90000,24.000000
35,West Bengal,23,71.60000,19.000000
36,Andaman & Nicobar Islands,21,70.43913,7.000000
37,NCT of Delhi,21,70.43913,12.000000
38,Dadra & Nagar Haveli,21,70.43913,16.000000
39,Jammu & Kashmir,21,70.43913,17.000000

In [140]:
# lif = []
# imr = []
# tdh = []
# for index, row in df.iterrows():
#     for index2,row2 in IMR_data.iterrows():
#         if row[1]==row2['State']:
#             lif.append(row2['Life Expectancy'])
#             tdh.append(row2['Total District Hospitals'])
#             imr.append(row2['IMR'])

# df['IMR'] = imr
# df['Total District Hospitals'] = tdh
# df['Life Expectancy'] = lif
# df.head(10)

df = df.drop(columns=["level_0","index"])
df.to_csv("District_IMR_ohd_indicators.csv")
df

,2,73,74,39,4,33,34,35,22,19,80,81,97,IMR,Total District Hospitals,Life Expectancy
0,South Andamans,85.9,88.1,89.8,43.2,21.1,17.4,12.6,81.7,79.0,89.3,97.9,86.7,19.027778,3,70.43913
1,Nicobars,71.7,85.1,92.5,48.0,21.6,24.6,15.7,67.3,69.1,83.5,98.8,87.5,19.027778,3,70.43913
2,North And Middle Andaman,79.2,92.5,94.3,47.8,27.0,42.8,27.0,0.0,0.0,86.4,92.2,84.0,19.027778,3,70.43913
3,Guntur,62.5,94.0,97.2,54.6,23.8,26.9,17.8,92.5,76.2,83.4,99.3,68.5,24.000000,14,70.00000
4,Spsr Nellore,73.0,95.5,94.3,68.6,29.2,27.8,17.2,81.1,69.4,81.8,95.6,70.5,24.000000,14,70.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728,Birbhum,78.4,67.5,81.7,78.6,37.0,41.8,25.5,98.4,84.8,55.0,99.4,70.8,19.000000,23,71.60000
729,Dinajpur Uttar,70.1,60.9,69.4,63.6,44.8,32.0,16.0,88.5,88.4,63.8,99.8,65.4,19.000000,23,71.60000
730,Nadia,71.2,89.4,89.9,68.2,26.1,25.1,17.6,95.0,92.6,78.4,98.2,76.2,19.000000,23,71.60000
731,Bankura,75.7,67.2,76.5,80.3,30.3,38.8,26.0,93.5,94.1,49.2,96.3,68.3,19.000000,23,71.60000
732,Darjeeling,79.2,73.9,84.7,60.1,34.3,31.6,20.6,100.0,95.9,83.0,90.8,77.0,19.000000,23,71.60000

In [100]:
# df = pd.read_csv("state_ohd_indicators.csv")
# # df
# # df= df.drop(columns=['index'])
# # df.unique()
# # Group by column '1' and calculate the mean for all other columns
# column_name = df.columns[0]  # Get the name of the column at index 1
# # column_name
# df_grouped = df.groupby(column_name).mean().reset_index()

# df_grouped.to_csv("state_ohd_indicators.csv")

### Weights to ohd indicators(District) without IMR,Hospitals & Life Expectency

In [2]:
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler


df = pd.read_csv('district_ohd_indicators.csv')
# df["2"]

# Separate the district column and the indicators
districts = df["2"]
indicators = df.drop(columns=["2",'index', '4','35', '22', '19','81'])
df = df.drop(columns=['4','35', '22', '19','81'])

# Step 1: Standardize the indicator columns
scaler = StandardScaler()
indicators_scaled = scaler.fit_transform(indicators)

# Step 2: Run PCA and get the first principal component
pca = PCA(n_components=1)
pca.fit(indicators_scaled)

# Extract the loadings (weights) of each indicator in the first principal component
pc1_loadings = pca.components_[0]

# Step 3: Convert loadings to absolute values and normalize to get weights
abs_loadings = abs(pc1_loadings)
weights = abs_loadings / abs_loadings.sum()

# Create a DataFrame to display weights for each indicator
weights_df = pd.DataFrame({
    'indicator': indicators.columns,
    'weight': weights
})

# Display the weights for each indicator
print("Weights for each indicator:")
print(weights_df)

# Step 4: Calculate the overall health condition score for each district
# Multiply each indicator by its weight and sum across columns
health_scores = indicators_scaled.dot(weights)

# Step 5: Add the health condition score to the original DataFrame
df['overall_health_condition'] = health_scores

# Display the updated DataFrame with the overall health condition score
print("\nDataFrame with Overall Health Condition Score: ")
print(df[["2", 'overall_health_condition']])

df = df.drop(columns=['index'])
df.to_csv("PCA_No_IMR_health_conditions_by_district.csv")

Weights for each indicator:
  indicator    weight
0        73  0.150039
1        74  0.146223
2        39  0.136341
3        33  0.156220
4        34  0.127846
5        80  0.133666
6        97  0.149665

DataFrame with Overall Health Condition Score:
                       2  overall_health_condition
0               Longding                 -1.027526
1         South Andamans                  0.321915
2    Lower Dibang Valley                 -0.825499
3           Spsr Nellore                  0.363930
4                  Kamle                 -0.644831
..                   ...                       ...
728              Vellore                  0.565464
729        Muzaffarnagar                  0.060293
730               Garhwa                 -0.294597
731          Uttar Kashi                 -0.018778
732   Pashchim Champaran                 -0.911663

[733 rows x 2 columns]

### Checking the States which is only in either supreme or in state

In [ ]:
IMR_data = pd.read_csv("supreme_merged_file.csv")
No_IMR_data = pd.read_csv("state_ohd_indicators.csv")

# Assuming the common column in both datasets is named 'common_column'
IMR_column_values = set(IMR_data['State'])
No_IMR_column_values = set(No_IMR_data['1'])

# Values in IMR_data that are not in No_IMR_data
unique_in_IMR = IMR_column_values - No_IMR_column_values

# Values in No_IMR_data that are not in IMR_data
unique_in_No_IMR = No_IMR_column_values - IMR_column_values

print("Values in IMR_data not in No_IMR_data:", unique_in_IMR)
print("Values in No_IMR_data not in IMR_data:", unique_in_No_IMR)

Values in IMR_data not in No_IMR_data: {'NCT of Delhi', 'Lakshadweep', 'Dadra & Nagar Haveli', 'Chandigarh', 'Jammu & Kashmir', 'Andaman & Nicobar Islands'}
Values in No_IMR_data not in IMR_data: set()

### Weights to ohd indicators(StateWise) with IMR,Hospitals & Life Expectency

In [1]:
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler


df = pd.read_csv('state_IMR_ohd_indicators.csv')
# df["2"]

# Separate the district column and the indicators
state = df["State"]
indicators = df.drop(columns=["index",'State'])
df = df.drop(columns=['4','35', '22', '19','81'])

# Step 1: Standardize the indicator columns
scaler = StandardScaler()
indicators_scaled = scaler.fit_transform(indicators)

# Step 2: Run PCA and get the first principal component
pca = PCA(n_components=1)
pca.fit(indicators_scaled)

# Extract the loadings (weights) of each indicator in the first principal component
pc1_loadings = pca.components_[0]

# Step 3: Convert loadings to absolute values and normalize to get weights
abs_loadings = abs(pc1_loadings)
weights = abs_loadings / abs_loadings.sum()

# Create a DataFrame to display weights for each indicator
weights_df = pd.DataFrame({
    'indicator': indicators.columns,
    'weight': weights
})

# Display the weights for each indicator
print("Weights for each indicator:")
print(weights_df)

# Step 4: Calculate the overall health condition score for each district
# Multiply each indicator by its weight and sum across columns
health_scores = indicators_scaled.dot(weights)

# Step 5: Add the health condition score to the original DataFrame
df['overall_health_condition'] = health_scores

# Display the updated DataFrame with the overall health condition score
print("\nDataFrame with Overall Health Condition Score:")
print(df[["State", 'overall_health_condition']])

df = df.drop(columns=['index'])
df.to_csv("PCA_IMR_health_conditions_by_state.csv")

Weights for each indicator:
                   indicator    weight
0   Total District Hospitals  0.058262
1            Life Expectancy  0.072728
2                        IMR  0.101446
3                         73  0.044139
4                         74  0.014884
5                         39  0.000750
6                          4  0.082507
7                         33  0.103230
8                         34  0.103996
9                         35  0.085297
10                        22  0.065445
11                        19  0.053141
12                        80  0.102126
13                        81  0.001465
14                        97  0.110584

DataFrame with Overall Health Condition Score:
                                           State  overall_health_condition
0                    Andaman And Nicobar Islands                 -0.341724
1                                 Andhra Pradesh                 -0.069880
2                              Arunachal Pradesh                 -0.558000
3                                          Assam                  0.193273
4                                          Bihar                  0.110284
5                                   Chhattisgarh                  0.169073
6                                          Delhi                  0.178603
7                                            Goa                 -0.392466
8                                        Gujarat                  0.578528
9                                        Haryana                 -0.049554
10                              Himachal Pradesh                  0.283156
11                             Jammu And Kashmir                  0.162399
12                                     Jharkhand                  0.099328
13                                     Karnataka                  0.151456
14                                        Kerala                 -0.126992
15                                        Ladakh                  0.000501
16                                Madhya Pradesh                  0.153744
17                                   Maharashtra                  0.449847
18                                       Manipur                 -0.818731
19                                     Meghalaya                  0.201466
20                                       Mizoram                 -0.367931
21                                      Nagaland                 -0.357610
22                                        Odisha                  0.202783
23                                    Puducherry                 -0.013789
24                                        Punjab                 -0.160309
25                                     Rajasthan                 -0.036889
26                                        Sikkim                 -0.579562
27                                    Tamil Nadu                 -0.023152
28                                     Telangana                  0.125747
29  The Dadra And Nagar Haveli And Daman And Diu                  0.443675
30                                       Tripura                 -0.030124
31                                 Uttar Pradesh                  0.249992
32                                   Uttarakhand                 -0.152654
33                                   West Bengal                  0.325509

### Weights to ohd indicators(DistrictWise) without IMR,Hospitals & Life Expectency

In [1]:
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler


df = pd.read_csv('district_ohd_indicators.csv')
# df["2"]

# Separate the district column and the indicators
state = df["2"]
indicators = df.drop(columns=["index",'2'])

# Step 1: Standardize the indicator columns
scaler = StandardScaler()
indicators_scaled = scaler.fit_transform(indicators)

# Step 2: Run PCA and get the first principal component
pca = PCA(n_components=1)
pca.fit(indicators_scaled)

# Extract the loadings (weights) of each indicator in the first principal component
pc1_loadings = pca.components_[0]

# Step 3: Convert loadings to absolute values and normalize to get weights
abs_loadings = abs(pc1_loadings)
weights = abs_loadings / abs_loadings.sum()

# Create a DataFrame to display weights for each indicator
weights_df = pd.DataFrame({
    'indicator': indicators.columns,
    'weight': weights
})

# Display the weights for each indicator
print("Weights for each indicator:")
print(weights_df)

# Step 4: Calculate the overall health condition score for each district
# Multiply each indicator by its weight and sum across columns
health_scores = indicators_scaled.dot(weights)

# Step 5: Add the health condition score to the original DataFrame
df['overall_health_condition'] = health_scores

# Display the updated DataFrame with the overall health condition score
print("\nDataFrame with Overall Health Condition Score:")
print(df[["2", 'overall_health_condition']])
df
# df = df.drop(columns=['index'])
# df.to_csv("PCA_IMR_health_conditions_by_district.csv")

Weights for each indicator:
   indicator    weight
0         73  0.112650
1         74  0.110824
2         39  0.102243
3          4  0.040198
4         33  0.113782
5         34  0.101786
6         35  0.062932
7         22  0.049776
8         19  0.063472
9         80  0.100141
10        81  0.033433
11        97  0.108762

DataFrame with Overall Health Condition Score:
                       2  overall_health_condition
0               Longding                 -1.169896
1         South Andamans                  0.120240
2    Lower Dibang Valley                 -0.791380
3           Spsr Nellore                  0.224679
4                  Kamle                 -0.621002
..                   ...                       ...
728              Vellore                  0.447957
729        Muzaffarnagar                 -0.005844
730               Garhwa                 -0.223324
731          Uttar Kashi                  0.000454
732   Pashchim Champaran                 -0.774825

[733 rows x 2 columns]

,index,2,73,74,39,4,33,34,35,22,19,80,81,97,overall_health_condition
0,0,Longding,39.600,57.100,55.500,37.700,15.800,13.800,20.600,61.500,52.700,83.500,62.50,70.200,-1.169896
1,1,South Andamans,85.900,88.100,89.800,43.200,21.100,17.400,12.600,81.700,79.000,89.300,97.90,86.700,0.120240
2,2,Lower Dibang Valley,48.600,58.600,58.400,39.400,14.300,9.700,7.600,84.400,77.800,89.900,99.50,80.000,-0.791380
3,3,Spsr Nellore,73.000,95.500,94.300,68.600,29.200,27.800,17.200,81.100,69.400,81.800,95.60,70.500,0.224679
4,4,Kamle,36.902,64.246,62.783,53.057,32.583,11.527,11.716,78.908,75.368,82.213,97.05,69.914,-0.621002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728,728,Vellore,95.400,98.600,96.700,47.200,29.800,19.700,13.100,95.500,93.900,76.200,97.70,81.600,0.447957
729,729,Muzaffarnagar,44.000,88.500,87.300,48.800,29.800,29.900,20.700,77.600,74.100,80.100,99.90,72.100,-0.005844
730,730,Garhwa,29.800,70.300,70.600,61.000,47.700,40.600,18.900,86.100,78.200,54.100,92.50,59.600,-0.223324
731,731,Uttar Kashi,66.800,72.000,72.400,66.100,34.100,23.500,10.600,95.800,86.200,75.700,96.10,80.100,0.000454
732,732,Pashchim Champaran,25.400,57.300,64.100,56.300,43.500,30.300,13.200,79.900,74.700,43.300,99.70,52.500,-0.774825

### Weights to ohd indicators(DistrictWise) with IMR,Hospitals & Life Expectency

In [3]:
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler


df = pd.read_csv('District_IMR_ohd_indicators.csv')
# df["2"]

# Separate the district column and the indicators
state = df["2"]
indicators = df.drop(columns=["index",'2'])

# Step 1: Standardize the indicator columns
scaler = StandardScaler()
indicators_scaled = scaler.fit_transform(indicators)

# Step 2: Run PCA and get the first principal component
pca = PCA(n_components=1)
pca.fit(indicators_scaled)

# Extract the loadings (weights) of each indicator in the first principal component
pc1_loadings = pca.components_[0]

# Step 3: Convert loadings to absolute values and normalize to get weights
abs_loadings = abs(pc1_loadings)
weights = abs_loadings / abs_loadings.sum()

# Create a DataFrame to display weights for each indicator
weights_df = pd.DataFrame({
    'indicator': indicators.columns,
    'weight': weights
})

# Display the weights for each indicator
print("Weights for each indicator:")
print(weights_df)

# Step 4: Calculate the overall health condition score for each district
# Multiply each indicator by its weight and sum across columns
health_scores = indicators_scaled.dot(weights)

# Step 5: Add the health condition score to the original DataFrame
df['overall_health_condition'] = health_scores

# Display the updated DataFrame with the overall health condition score
print("\nDataFrame with Overall Health Condition Score:")
print(df[["2", 'overall_health_condition']])
# df
df = df.drop(columns=['index'])
df.to_csv("PCA_IMR_health_conditions_by_district.csv")

Weights for each indicator:
                   indicator    weight
0                         73  0.086365
1                         74  0.068528
2                         39  0.061499
3                          4  0.042623
4                         33  0.097123
5                         34  0.091585
6                         35  0.052667
7                         22  0.020452
8                         19  0.033108
9                         80  0.088324
10                        81  0.012556
11                        97  0.102608
12                       IMR  0.085492
13  Total District Hospitals  0.064883
14           Life Expectancy  0.092187

DataFrame with Overall Health Condition Score:
                            2  overall_health_condition
0              South Andamans                 -0.010033
1                    Nicobars                 -0.037249
2    North And Middle Andaman                  0.052120
3                      Guntur                  0.016828
4                Spsr Nellore                  0.132489
..                        ...                       ...
728                   Birbhum                  0.233943
729            Dinajpur Uttar                 -0.004487
730                     Nadia                  0.160589
731                   Bankura                  0.058645
732                Darjeeling                  0.296286

[733 rows x 2 columns]